# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-22.04, ubuntu-latest]
                java: [17, 21]
                arch: [x64] # when ARM will be present add aarch64
            fail-fast: false
            max-parallel: 4
        name: Test JDK ${{ matrix.java }}, ${{ matrix.os }}

        steps:
            - name: Check out repository
              uses: actions/checkout@v2

            - name: Cache maven repository
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.m2/repository
                  key: ${{ matrix.arch }}-${{ runner.os }}-maven-${{ matrix.java }}-${{ hashFiles('**/pom.xml') }}
                  restore-keys: |
                      ${{ matrix.arch }}-${{ runner.os }}-maven-${{ matrix.java }}
                      ${{ matrix.arch }}-${{ runner.os }}-maven

            - name: Set up JDK
              uses: actions/setup-java@v1
              with:
                  java-version: ${{ matrix.java }}
                  architecture: ${{ matrix.arch }}
            - name: Test with Maven
              run: mvn verify -B --file pom.xml

